platform :ios, '7.0'

pod 'AFNetworking', '~> 2.1.0'
pod 'Facebook-iOS-SDK', '~> 3.17.0'
pod 'Mantle', '~> 1.3.1'
pod 'ReactiveCocoa'
pod 'AFNetworking-RACExtensions', :git => 'https://github.com/knshiro/AFNetworking-RACExtensions.git'
pod 'AFNetworkActivityLogger', '~> 2.0.1'
pod 'AMAttributedHighlightLabel', :git => 'https://github.com/johnkchow/AMAttributedHighlightLabel.git'
#pod 'AMAttributedHighlightLabel', :path => '~/Source/AMAttributedHighlightLabel'
